image: crowdar/lippia:3.1.2.2
pipelines:

#################### Manual pipeline configuration #####################
  custom:
    pipeline-manual: 
      - variables:          
          - name: TAG
            default: "@Success"
          - name: TESTTYPE
            default: "Secuencial"          
          - name: LANG
            default: "@EN"
      - parallel:
          steps:
            - step: 
                name: Print variables
                script:
                  - |
                     echo "'TAG= $TAG'"
                     echo "'TESTTYPE= $TESTTYPE'"
                     echo "'LANG= $LANG'"
            - step:
                name: Test Lippia
                image: crowdar/lippia:3.1.2.2
                script: 
                  - git clone https://<BITBUCKET_USER>:<BITBUCKET_PASS>@bitbucket.org/path/to/your/<AUTOMATION_PROJECT>.git
                  - cd <AUTOMATION_PROJECT>
                  - mvn test -P$TESTTYPE -Dcrowdar.cucumber.filter="'$TAG'" -Dcrowdar.cucumber.filter.language="'$LANG'" || true
                  - apt-get install -y zip && cd target/reports && zip -r artifact.zip *
                  - pipe: atlassian/bitbucket-upload-file:0.3.3
                    variables:
                      BITBUCKET_USERNAME: '<YOUR_USERNAME>'
                      BITBUCKET_APP_PASSWORD: '<YOUR_BITBUCKET_APP_PASSWORD>'
                      FILENAME: 'artifact.zip'
                      
 
 ###################### Auto pipeline configuration ####################

  default:  
      - parallel:       
          steps:
            - step: 
                name: Print variables
                script:
                  - |
                     echo "'BITBUCKET_TAG= $BITBUCKET_TAG'"
                     echo "'BITBUCKET_TESTTYPE= $BITBUCKET_TESTTYPE'"
                     echo "'BITBUCKET_LANG= $BITBUCKET_LANG'"
            - step:
                name: Test Lippia
                image: crowdar/lippia:3.1.2.2
                script: 
                  - git clone https://<BITBUCKET_USER>:<BITBUCKET_PASS>@bitbucket.org/path/to/your/<AUTOMATION_PROJECT>.git
                  - cd <AUTOMATION_PROJECT>
                  - mvn test -P$BITBUCKET_TESTTYPE -Dcrowdar.cucumber.filter="'$BITBUCKET_TAG'" -Dcrowdar.cucumber.filter.language="'$BITBUCKET_LANG'" || true
                  - apt-get install -y zip && cd target/reports && zip -r artifact.zip *
                  - pipe: atlassian/bitbucket-upload-file:0.3.3
                    variables:
                      BITBUCKET_USERNAME: '<YOUR_USERNAME>'
                      BITBUCKET_APP_PASSWORD: '<YOUR_BITBUCKET_APP_PASSWORD>'
                      FILENAME: 'artifact.zip'
                  
